name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag gehal6/kantoxapp:$GITHUB_SHA
    - name: get image id
      run: echo "imageid=`docker images | grep -i  kantoxapp | grep -i $GITHUB_SHA | awk '{print $3}'`" >> $GITHUB_ENV
    - name: tag image as latest
      run: docker tag "${{ env.imageid }}"  gehal6/kantoxapp:latest
    - name: push image as latest
      run: docker push gehal6/kantoxapp:latest
    - name: push image with sha
      run: docker push gehal6/kantoxapp:$GITHUB_SHA
